```{r}
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
```


```{r}
# .tif = raster, .gpkg = vector data
# Vectors use sf package, rasters use stars
ei_points <- st_read(here("discussions", "w1discussion", "data", "easter_island", "ei_points.gpkg")) |> 
  filter(type == "volcano")
ei_elev <- read_stars(here("discussions", "w1discussion", "data", "easter_island", "ei_elev.tif"))
ei_borders <- st_read(here("discussions", "w1discussion", "data", "easter_island", "ei_border.gpkg"))
ei_roads <- st_read(here("discussions", "w1discussion", "data", "easter_island", "ei_roads.gpkg"))
```


```{r}
dim(ei_points) # Filtered df 36 rows, 5 cols
```


```{r}
tm_shape(ei_borders) +
    tm_borders() +
    tm_layout(main.title = "Easter Island")
```


```{r}
tmap_mode("view")
tm_shape(ei_elev) +
tm_graticules() +
    tm_raster(col.scale = tm_scale_continuous(values = '-rd_yl_gn'), # tm_scale_continuous() for smooth gradient instead of bins. Red to yellow to green palette. Minus reversed it.
                col.legend = tm_legend('Elevation (m asl)')) + # Set legend title with units
tm_shape(ei_borders) +
    tm_borders() +
tm_shape(ei_roads) +
    tm_lines() +
tm_shape(ei_points) +
    tm_symbols(shape = 24,
                size = 'elevation',
                size.legend = tm_legend('Volcanoes (m asl)')) +
tm_compass(position = c('right', 'top')) +
tm_scalebar() +
tm_title('Easter Island') +
tm_legend(position = tm_pos_out('right', 'center'))

tmap_mode("plot")
```

```{r}
library(ggspatial)
```

```{r}
# extract lat & long from geom column 
volcanoes_point <- ei_points %>%
  mutate(lon = unlist(map(ei_points$geom,1)), # longitude = first component (x)
         lat = unlist(map(ei_points$geom,2))) # latitude = second component (y)
```


```{r}
ggplot() +
  # first add Easter Isand borders
  geom_sf(data = ei_borders, color = "#212529") +
  # add elevation raster
  geom_stars(data = ei_elev) +
  scale_fill_distiller(name = "Elevation (m asl)", # legend title with units
                       palette = "RdYlGn",         # red-yellow-green palette (no need to reverse)
                       na.value = "lightblue") +  # set NA color (background ocean)
  # add road vector
  geom_sf(data = ei_roads, color = "#343a40") +
  # add volcano vector
  geom_point(data = volcanoes_point, 
             aes(x = lon, y = lat, 
                 size = elevation), # point size depends on attribute value
             shape = 17,            # triangle
             color = "#22577a") +
  scale_size_continuous(name = "Volcanoes (m asl)") +       # legend title with units
  ggspatial::annotation_north_arrow(location = "br",        # bottom right
                                    which_north = "true") + # point to north pole
  ggspatial::annotation_scale(location = "bl",              # bottom left
                              width_hint = 0.5) +           # proportion of map area the scalebar should occupy
  labs(title = "Easter Island") +
  theme_minimal()
```